<?php

namespace TV\CongresBundle\Repository;

/**
 * CongressRegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CongressRegistrationRepository extends \Doctrine\ORM\EntityRepository
{
    public function listCongressRegistration($congres) {
        $qb = $this
            ->createQueryBuilder('a')
            ->where('a.congres = :congres')
            ->setParameter('congres', $congres)
        ;
        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
    public function yourRegistration($congres, $user) {
        $qb = $this
            ->createQueryBuilder('a')
            ->where('a.congres = :congres')
            ->setParameter('congres', $congres)
            ->andWhere('a.user = :user')
            ->setParameter('user', $user)
        ;
        return $qb
            ->getQuery()
            ->getSingleResult()
        ;
    }
}
