<?php

namespace TV\CongresBundle\Repository;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends \Doctrine\ORM\EntityRepository
{
    public function getStateOld(){
        $qb = $this
            ->createQueryBuilder('a')
            ->where('a.id = 3')
            ->setMaxResults(1)
            ->getQuery()
        ;
        
        return $qb->getSingleResult();
    }
}
